version: '3'
services:
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: envelopes
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: envelopes

  node:
    build:
      dockerfile: docker/node/Dockerfile
      context: .
      args:
        - UID=${UID}
    restart: unless-stopped
    user: ${UID}:${UID}
    ports:
      - 3333:3333
    entrypoint: npm
    command: run dev
    volumes:
      - ./:/home/node/app

volumes:
  postgres-data:
